title: "Cards"
description: |
  Cards can be used as a template for any sections of the website.

patterns:
  basic:
    title: "Basic"
    description: |
      A simple card that contains a title, description and a call to action.
    fields:
      - name: data
        type: object
        data:
          source: "site.pieces[0]"
          type: piece
  portfolio:
    title: "Portfolio"
    description: |
      A card to display all portfolio pieces. It contains descriptions and placeholders for portfolio images.
    fields:
      - name: data
        type: object
        data:
          source: "site.pieces[0]"
          type: piece
  portfolio-2:
    title: "Portfolio-2"
    description: |
      A card to display all portfolio pieces. It contains descriptions and placeholders for portfolio images.
    fields:
      - name: data
        type: object
        data:
          source: "site.pieces[0]"
          type: piece
  portfolio-3:
    title: "Portfolio-3"
    description: |
      A card to display all portfolio pieces. It contains descriptions and placeholders for portfolio images.
    fields:
      - name: data
        type: object
        data:
          source: "site.pieces[0]"
          type: piece
    portfolio-4:
      title: "Portfolio-4"
      description: |
        A card to display all portfolio pieces. It contains descriptions and placeholders for portfolio images.
      fields:
        - name: data
          type: object
          data:
            source: "site.pieces[0]"
            type: piece
  portfolio-5:
    title: "Portfolio-5"
    description: |
      A card to display all portfolio pieces. It contains descriptions and placeholders for portfolio images.
    fields:
      - name: data
        type: object
        data:
          source: "site.pieces[0]"
          type: piece
